In [1]:
import numpy as np

In [2]:
pprint

Pretty printing has been turned OFF


In [3]:
dir(np)

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [4]:
arr1=np.array([10,20,30,40,50])
arr1

# 1D data
# numpy array

array([10, 20, 30, 40, 50])

In [5]:
arr1.shape

(5,)

In [6]:
arr1[0]

#retrives data based on index

10

In [9]:
arr1[2:4]

#slicing can also be done

array([30, 40])

In [11]:
l1=[100,200,300,400,500]
l1

# list

[100, 200, 300, 400, 500]

In [12]:
len(l1)

5

In [13]:
l1[0]

100

In [ ]:
# byte,short,int,long

In [14]:
import numpy as np
import time
import sys

In [15]:
sys.getsizeof(1)

28

In [16]:
sys.getsizeof(148)

28

In [17]:
sys.getsizeof(8500)

28

In [19]:
sys.getsizeof(777777777)

28

In [20]:
r1=range(100)

In [21]:
print(*r1)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


In [22]:
sys.getsizeof(99)

28

In [23]:
28*100

2800

In [24]:
5*28

140

In [25]:
l2=[100,200,300,400,500]
print(sys.getsizeof(500)*len(l2))

140


In [27]:
arr2=range(100)
print(*arr2)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


In [29]:
arr3=np.array([100,200,300,400,500])
arr3

array([100, 200, 300, 400, 500])

In [30]:
arr3.itemsize

4

In [31]:
5*4

20

In [32]:
#time checking

In [33]:
list1=range(100)
list2=range(100)

In [35]:
array1=np.arange(100)
array2=np.arange(100)

In [37]:
time.time()

#current time
#julian number

1758289449.1751924

In [38]:
start_time=time.time()
start_time

1758289474.5854418

In [39]:
list=[n for n in range(1,11)]
list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [40]:
list=[n+n for n in range(1,11)]
list

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [41]:
list[2:7]

[6, 8, 10, 12, 14]

In [42]:
array=np.array([[1,2],[8,9],[8,5]])
array

array([[1, 2],
       [8, 9],
       [8, 5]])

In [43]:
array.ndim

2

In [44]:
array.itemsize

4

In [45]:
array.dtype

dtype('int32')

In [46]:
array.size

6

In [47]:
array.shape

#rows and columns

(3, 2)

In [48]:
array[0]

array([1, 2])

In [50]:
arr6=np.array([[1,2],[3,4],[5,6]],dtype=complex)
arr6



array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [51]:
arr7=np.zeros((3,4))
arr7

#generating zeros in 3 rows 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
arr7.shape

(3, 4)

In [54]:
arr7.dtype

dtype('float64')

In [55]:
arr8=np.ones((4,3))
arr8

#generating ones in 4 rows 3 columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
r1=range(5)
print(*r1)

0 1 2 3 4


In [57]:
r1[0]

0

In [58]:
r1[3]

3

In [60]:
arr9=np.arange(5)
arr9

# printing values from 0 to 4

array([0, 1, 2, 3, 4])

In [62]:
arr10=np.arange(0,50,5)
arr10

#printing values from 0 to 50 by 5 variation

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [65]:
np.linspace(1,10,10)

# between 1 to 10 I want 10 elements

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [67]:
np.linspace(1,5,10)

# from 1 to 5 I want 10 values

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [68]:
arr12=np.array([[1,2],[3,4],[5,6]])
arr12

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
arr12.shape

(3, 2)

In [70]:
arr12.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
arr12.reshape(6)

array([1, 2, 3, 4, 5, 6])

In [72]:
arr12.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [73]:
arr12.ndim

2

In [74]:
arr12.ravel()

# returns n-dimensional data into single dimension

array([1, 2, 3, 4, 5, 6])

In [75]:
arr12.min()

1

In [76]:
arr12.max()

6

In [77]:
arr12.sum()

21

In [78]:
arr12.mean()

3.5

In [79]:
arr12.std()

1.707825127659933

In [81]:
arr12.strides

# each elements is taking 4 bytes
# 8 bytes of memory is required to move into next row

(8, 4)

In [82]:
arr13=np.array([[1,2,4],[4,6,7]])
arr13

array([[1, 2, 4],
       [4, 6, 7]])

In [83]:
arr13.strides

(12, 4)

In [84]:
arr13.sum(axis=0)

#columns

array([ 5,  8, 11])

In [85]:
arr13.sum(axis=1)

#rows

array([ 7, 17])

In [86]:
a1=np.array([1,2,4])
a2=np.array([9,8,7])

In [88]:
a1.dot(a2)

53

In [89]:
a1+a2

array([10, 10, 11])

In [90]:
a1 @ a2

53

In [91]:
np.dot(a1,a2)

53

In [93]:
np.vstack((a1,a2))

#vertical stacking

array([[1, 2, 4],
       [9, 8, 7]])

In [94]:
np.hstack((a1,a2))

#horizontal stacking

array([1, 2, 4, 9, 8, 7])